### ISSUE TITLE
Implement binary colvars trajectory file

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#105]
Using 32-bit floats, would reduce the size by a factor of 5, and would be faster to read and process for large-scale analysis programs.

**Comment by giacomofiorin** [comment]
I have already some code (not finished yet) that allows for binary I/O through overloading of the formatted I/O stream operators.  This would allow using the existing I/O functions.

Aside from that basic infrastructure, I see three requirements to satisfy this:
1) Handling incomplete writes or reads, essential particularly for trajectory files that get truncated when a simulation runs out of time.
2) Allowing the option to tune the precision: for example, if one tries to calculate the accumulated work of a bias in post-processing of a long trajectory, 64-bits may be useful.  The XTC routines of GROMACS (based on the XDR API) work fairly well and could be taken as example.
3) Allowing binary I/O through the scripting interface, so that a file format can be used by a linked shared object, similarly to what `gettimestep` or `rawtimestep` can be used for in VMD.  (Accordingly, I just closed #37, which has now become part of this.)  Do you object to start by changing the prototype `cv` Tcl proc to one that processes `Tcl_Obj` arguments instead of C strings?

**Comment by giacomofiorin** [comment]
Never mind about XDR, I notice now that there is no established open-source Windows port.

**Comment by akohlmey** [comment]
What about the XDR routines in LAMMPS or VMD? They work just fine on windows and have been in use for many years.
But you really don't have to go that far. You can basically do native binary output from C++ (or C) without a problem, when you follow two simple rules:
1. Have a fixed size, canonical header where you have a "magic number", a version tag, and flags for endianness as well as the size of all data types used.
2. Prefix each block of output with a small section containing a (string) label (the key) and the length (in bytes) and the number items and type of the following data (thus allowing for padded data blocks)

**Comment by giacomofiorin** [comment]
Good point, I didn't check the LAMMPS version.  Anyway, I'll push soon what I have so far.

**Comment by jhenin** [comment]
I see no problem at all with having the cv proc have a Tcl_obj as its argument.

**Comment by jhenin** [comment]
No need to be reminded of this in the short term. This will happen eventually as a consequence of other improvements.
