### ISSUE TITLE
Remove code opening history files with append flag

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#136]
To that effect, `colvarbias_abf::write_gradient_samples()` should take an ostream parameter instead of a filename, so history files can be kept open just like trajectory files.

**Comment by giacomofiorin** [comment]
To keep a history of the ABF files, would you consider switching the same convention used in metadynamics (writing the files as they are, but include the step number in the file name) and share everything in the base class?  I would be happy to make that a part of the workflow in `colvarbias::write_output_files()` so that we only need to maintain a single infrastructure.

**Comment by jhenin** [comment]
Difficult choice. On the one hand, there is a clear benefit to having a shared infrastructure. But I'm afraid it puts an additional burden on users - one it adapting their analysis scripts, the other is handling a larger number of files. The number of files generated by ABF - and particularly eABF simulations is already somewhat impractical.

I'm all for sharing that code, but can we retain the option to write to a single file? Then we'd keep backwards compatibility with both types of biases.

**Comment by giacomofiorin** [comment]
The implementation of the shared options could remain different (for as
long as we avoid appending to files).  What I'm suggesting is primarily l
that we call the relevant functions with the same schedule:
- writing every outputFreq (and moving it to the base class)
- writing on request by a script command.

**Comment by jhenin** [comment]
Sounds good. Would you rather start writing the base class implementation, if you have specific ideas about it? Otherwise I can do it.
