### ISSUE TITLE
Colvars example in LAMMPS still failing after last update

### ISSUE THREAD

**Issue by akohlmey** [Colvars/colvars#141]
There is no longer a segfaults, but running the examples/USER/colvars/in.peptide-colvars example now aborts prematurely when restarting with:
```
colvars: ----------------------------------------------------------------------
colvars: Collective variables biases initialized, 1 in total.
colvars: ----------------------------------------------------------------------
colvars: Collective variables module (re)initialized.
colvars: ----------------------------------------------------------------------
colvars: Re-initialized atom group one:0/0. 4 atoms: total mass = 4.
colvars: Re-initialized atom group one:0/1. 1 atoms: total mass = 1.
colvars: Re-initialized atom group two:0/0. 4 atoms: total mass = 4.
colvars: Re-initialized atom group two:0/1. 1 atoms: total mass = 1.
colvars: Error: in opening input file "out.colvars.state".
ERROR on proc 0: Fatal error in the collective variables module.
 (../colvarproxy_lammps.cpp:308)
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor
```
Could it be, that the input deck needs to be updated?

**Comment by giacomofiorin** [comment]
Hum, this breaks the NAMD tests, too...  I'll talk to you and @rbberger about advice on hooking up a Jenkins server.

**Comment by giacomofiorin** [comment]
@akohlmey I would like to change that input after all, since the default "out.colvars.state" doesn't seem too clear (different runs would overwrite each other).  I'd rather have Colvars keep bundling its state with the LAMMPS restart, and output its own text file only when requested.  I also have more examples of actual PMF calculations.

Anyway, here there is an issue with the state file not being written, and it looks to be compiler dependent (works with gcc 4.8, breaks with 6.3).  More so, at least in the case of NAMD it appears sensitive to the number of threads (1 works, >1 fails). The issue goes a few weeks back, though, and I only noticed it now after I checked on my home machine.  @jhenin Can you reproduce it and if so, try to see if its related to the static `colvardeps` members?

**Comment by giacomofiorin** [comment]
@jhenin I assigned you until you figure out whether there is any issue with `colvardeps` members.  If not, please assign me.

**Comment by jhenin** [comment]
I can reproduce this in LAMMPS, but not in NAMD. I tried gcc versions 4.8, 5.4, and 6.3. With 6.3 I do get some regtest failures due to numerical deviation on the order of 1e-6.

I'm confused about the LAMMPS input though. It does write a restart file under "rest.colvars.state", although only every 1000 steps with the current settings. I'm not sure when "out.colvars.state" is supposed to get written.

**Comment by giacomofiorin** [comment]
I found the error, and it is due to a previous assumption that output files were to be written only upon deallocation.  The fix also addresses the issue that the "restart" file (necessary for checkpointing the simulation) should be written in a separate call from files such as the PMFs, which are the actual "products", or "output" files.  In NAMD we are forced to call the "restart" file an "output" file due to the way it treats its own restart files.  In LAMMPS, the separation is clearer.

@akohlmey Thank you for bringing up the error.  The LAMMPS interface now checks whether `
_lmp->update->ntimestep == _lmp->update->laststep`: this seems safer than `_lmp->update->ntimestep == _lmp->update->endstep` but I can switch to the latter if more appropriate.

**Comment by giacomofiorin** [comment]
@jhenin I still see the error in NAMD after fixing the LAMMPS error.  Did you try a `multicore` build with multiple threads?  With 6.3 and one thread, I see the small deviations that you also observed, but with multiple threads the output files aren't written.  With 4.8, all is OK.  It is also not OpenMP-related because I'm still using a Charm++ built with CkLoop rather than the new OpenMP support.

**Comment by giacomofiorin** [comment]
All's good on the NAMD front as well... This turns out to be a new feature in Charm++ 6.8 that prevents you from using more threads than the available CPU cores (the NAMD regtests use 3 threads, and I have a pretty old laptop). The small deviations with the newer compiler remain.  (What was confusing was that the outcome - files not being written - was the same as the genuine LAMMPS error.)
