### ISSUE TITLE
Restraints should not accept options they don't implement

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#147]
Specifically: harmonicWalls does not implement moving restraint options such as "targetCenters" and "targetForceConstant", so it should throw an error when they are provided.

**Comment by giacomofiorin** [comment]
@jhenin Can you provide a test input? If I enable `targetCenters` for a `harmonicWalls` it does give me an error.  As for `targetForceConstant`, it should be implemented unless I made a mistake.

**Comment by jhenin** [comment]
Thanks, I see that part of the code now. Collaborator might be using a slightly older version, I'm checking with them.

**Comment by jhenin** [comment]
Unconfirmed.

**Comment by jhenin** [comment]
Confirmed in tests. When only one wall was defined, the relative force constant wrt force_k was not setup. I fixed that in b68dc1f51387626249af3db6a054a90019708980.

I also replaced the factor `force_k` with the geometric mean of the two force constants instead of their product, because in case of a changing force constant, that would have been broken by colvarbias_restraint_k_moving::update(): `force_k = starting_force_k + (target_force_k - starting_force_k) * std::pow(lambda, force_k_exp); ` (l. 558).

Now, if the two wall constants are equal initially, force_k retains their common initial value and evolves as expected.

@giacomofiorin  Can you please have a quick look and confirm if it seems reasonable?

**Comment by giacomofiorin** [comment]
@jhenin I'm working at reduced speed today (baby-sitting at home) but I'll look closely tomorrow.  For sure one thing that we need is tests of each sub-case since their handling is now more robust.

**Comment by giacomofiorin** [comment]
@jhenin Thanks for addressing the case where one of the two sets of walls is absent.  I had added support for that only to be compatibile with the older `colvar`-based kewyords.

That said, I'm not sure whether you got always correct results with the latest version, because `starting_force_k` should have been initialized, but its only initialization was from the initial value of `forceConstant`, which may or may not be given.  In commit 3bf0ded I added this initialization, as well as clarifying the diagnostic messages about for both wall constants.  The force constants are now also set to -1 in the constructors, to spot any future bugs more easily.

It is still a bit confusing to define a single `targetForceConstant` when `lowerWallConstant` and `upperWallConstant` are chosen independently, but I don't see a way to avoid it without adding duplicated code again.  I added a bit more explanation in the manual for `targetForceConstant`.

Please check whether this works for your use case, and if so close the issue.

**Comment by giacomofiorin** [comment]
How does the current code work for this case?

**Comment by jhenin** [comment]
Working!
