### ISSUE TITLE
Bias energy from wall constants

### ISSUE THREAD

**Issue by binzhangMIT** [Colvars/colvars#158]
Dear developers, 

It seems to me that the bias energies that arise from "upperWall" or "lowerWall" are not added to the colvar energy. I was mainly looking at the "colvar.cpp" file, and it seems to me that only biasing forces are added, but not the energies. Is there a particular reason for why this is the case?

Thanks,
Bin

**Comment by giacomofiorin** [comment]
Hi @binzhangMIT what version do you refer to? The older version of the walls, which had them defined in `colvar.cpp`, did not include their contribution to the energy. However, since commit 31c803b these are now a proper bias. If the energy is not reported by the current version, please post a minimal input to reproduce the bug and I'll reopen the issue.

**Comment by binzhangMIT** [comment]
my bad. I was indeed looking at an older version of the code. should have checked the latest version before asking questions. Great work, by the way.
Bin

**Comment by giacomofiorin** [comment]
Thanks.  With which MD code are you using it?
