### ISSUE TITLE
Use of heterogeneous reference structures in CV definition

### ISSUE THREAD

**Issue by flblanc** [Colvars/colvars#161]
Dear colvars developpers,

When trying to define a CV (e.g. an RMSD) with a reference structure with a different number of atoms from the entire system (e.g. the reference only contains the protein atoms, whereas the full system also includes water and ions) I obtain the following error:

`Error: the number of records in the PDB file "./ref-structure.pdb" does not appear to match either the total number of atoms, or the number of coordinates requested at this point`

This error arises only for recent development builds of NAMD (I first noticed it back in April); the same syntax worked fine (and produced the intended behavior) in older versions (e.g. November 2017). Is there any particular reason for this change, and is it possible to revert to the old behavior?

**Comment by jhenin** [comment]
Hi Florian!

The rationale was mostly to get another chance to detect some setup errors in the form of mismatched files. Specifically, we reasoned that most users will either use the complete system files, or prepare a dedicated file for colvars - in which case the dedicated file needs only contain the relevant atoms.

This change was introduced because it did catch errors, so we'd need a good reason to revert it, but we are open to a substantial discussion on this (that is, one that does not depend on an overly specific workflow, see https://xkcd.com/1172).

In your case I suppose the atoms are identified by PDB flags? One possible case that comes to mind is a PDB file containing ref coordinates for multiple colvars, and yet not the full system. Then each atom set could be identified by a different PDB flag.

**Comment by flblanc** [comment]
Dear Jérôme,

Thank you for your reply; 

"In your case I suppose the atoms are identified by PDB flags? One possible case that comes to mind is a PDB file containing ref coordinates for multiple colvars, and yet not the full system. Then each atom set could be identified by a different PDB flag."

This is exactly the situation I am in. Another reason is that I am dealing with several water boxes of the same protein, but with different numbers of water molecules. As such it made sense for me to use the PDB file containing only the protein atoms to define the colvars, as it allowed to use the same CV definition for all the various versions of the system. 

I can understand the rationale behind your decision, but as a user I did prefer the previous implementation as I think it allowed for a more streamlined usage of the module. 

All the best,

**Comment by giacomofiorin** [comment]
Hi Florian, I presume this is the commit that changed the behavior, am I correct?
https://github.com/Colvars/colvars/commit/9b85d5f43b0a05ef43e25e5bf6ec189b71e3f4f3
The change doesn't impact the error condition that Jérôme refers to (which is older), but I had to be more rigid regarding the state of the input parameters of the PDB loading function to fix another error with out-of-order atom selections (which is probably not your case).

It may be possible to relax the check again without losing the newer error fix, but I'll need a few days to look into.

Jérôme, if you have some time to look into it by any chance, the change in behavior for Florian is probably caused by my calling `load_coords()` with the pre-allocated vector called `sorted_pos`.  It may be possible to let `load_coords()` allocate it, and similarly allocate `pos` before mapping the sorted positions into the out-of-order set of positions that RMSD uses,

**Comment by jhenin** [comment]
@flblanc Did this change resolve the issue on your side?

**Comment by flblanc** [comment]
Sorry for the late reply - with version 2018-12-18 things seem to work fine. Thanks a lot !
