### ISSUE TITLE
Dihedral caulcation fails when using cv update in VMD

### ISSUE THREAD

**Issue by benjamin-hilton** [Colvars/colvars#166]
The calculation of dihedrals in each frame of an already-complete simulation produces wrong values when calculated using `cv update` from the Tk console in VMD. The same colvars configuration file produces correct values when calculated in parallel with a simulation in NAMD and output to a trajectory file. These correct values are equal to those output by the VMD `measure dihed`command. The wrong values appear to be uniformly distributed in the [-180 : 180] interval.

The issue does not exist with RMSD or angles - the values output in the trajectory file from the NAMD simulation are in these cases equal to those output using `cv update` and `cv printframe`.

**Comment by giacomofiorin** [comment]
Hello Benjamin, can you share more details about the system and its
configurations?  What are the boundary conditions detected by VMD?

**Comment by jhenin** [comment]
Specifically, if this is a non-periodic simulation in NAMD, this kind of problem could happen because VMD's DCD file reader when reading a file with no unit cell info will set a "fake" unit cell with sizes of 1 Angstrom. And NAMD will write similarly wrong vectors when explicitly asked to do so (`DCDunitCell on` ). The workaround is `pbc set {0 0 0 90 90 90}` in VMD. Actual fixes are in the works.

**Comment by benjamin-hilton** [comment]
Thanks everyone! Yes, this was a non-periodic simulation in NAMD, which VMD appears to be detecting with wrong boundary conditions. However, the workaround, when entered into VMD before running `cv update`, appears to leave the results unchanged.

**Comment by jhenin** [comment]
The example I gave was for a single frame. For the whole trajectory: `pbc set {0 0 0 90 90 90} -first 0 -last last`
