### ISSUE TITLE
Enhancements to scripting interface

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#168]
These would be specifically useful for the VMD GUI "Colvars dashboard"

- [x] get config strings for colvars including comments (save before stripping)
- [x] get config string for the whole module
- [x] access atom groups from colvars->cvcs
- [x] clear index groups to allow reloading file

More generally, some script access to config parsing functions?

**Comment by giacomofiorin** [comment]
The PR #172 contains solutions to items 2 and 4.

For item 1, I'm not sure how to go about it without changes to the lower-level parser: because comment characters are taken into account when finding opening and closing braces, we would need to change how braces are handled.

For item 3, can you specify what you had in mind?  A list of atom IDs seems reasonable, but let's make sure first that that's sufficient.

**Comment by jhenin** [comment]
PR #172  looks great already!

I see the problem for item 1... From the perspective of the GUI, the alternative would be to remember the config strings that are passed to Colvars for parsing, but this runs the risk of getting out of sync if the config is changed independently from the GUI. The nice thing about querying the config in real time is that it's very robust to external changes.

For item 3, a list of lists of atom IDs would be perfect. Alternately, a way to query each group individually avoiding nested lists makes things simpler...

**Comment by jhenin** [comment]
(in-person conversation GF & JH) Clarifying the requirement for item 1: that is assuming the object is created based on a single config string. Once it can be modified by parsing partial config strings, one cannot rely on such a string to recreate it. Usage by the Dashboard will be limited to the classic workflow: 1 object = 1 monolithic config string.

**Comment by giacomofiorin** [comment]
The main issue stopping from implementing the remaining item (retaining comments in the config strings of individual object, as done for the whole module already) is that the parser assumes that comments are stripped before any of the following:
- parsing of global keywords;
- counting braces
- check for unknown/misspelled keywords.

This behavior can be modified, but it would take some time and require changes to the lower-level parsing functions.

Can the equivalent be achieved just by keeping the config string in Tcl?  This would work if the main use of this feature is within the Dashboard.  I understand that this is difficult to do when importing an existing configuration file.  But it could be made a lot simpler by incorporating tags as comments when a config file is generated in the Dashboard:
```
#CV-Dashboard
colvarsTrajFrequency 1000

#CV-Dashboard
colvar {
  ...
}

#CV-Dashboard
harmonic {
  ...
}
```

The comments may potentially include fields specific to the Dashboard that may become useful in the future, without creating a dependency/incompatibility in the Colvars module.

**Comment by jhenin** [comment]
It is possible to preserve the config strings at the Tcl level, but the config strings that were passed to Colvars at a certain point may not correspond to the state of the module at a later point in time, mostly because individual variables can be deleted and added in the meantime. Knowing whether any of that has happened would require the Dashboard to do its own parsing of the input, to determine what part of the string contains the config to which colvar. The reason that is non-trivial is because a single string entered in the Dashboard can define several colvars: that is intentional, and very useful in several workflows where variables can be combined or duplicated to create variants. Anyway, requiring that an input contains a single colvar would itself require some parsing.

If we want the config string for a given colvar, including comments, some code would have to low-level parse the full string, comments included, at least detecting brace-delimited blocks and the keyword "colvar". If the C++ parser cannot do that - and I see how implementing that can be a problem - then the Tcl code would have to do it.

An alternative would be for the dashboard to present not the full config string parsable by CVM, but the contents on the colvar {} block itself, which would then be added around the contents when saved or passed to CVM for parsing. This would leave to the module some responsibility for formatting (eg. do we indent the contents of the block?) and require a new approach to the workflows I mentioned above. Such as explicit controls to combine or duplicate variables.

**Comment by giacomofiorin** [comment]
I see, if you are passing more than one variable from the Dashboard, then it's not possible to do as I suggested.

The problem at the C++ level is similar to the Tcl Dashboard: you cannot identify brace-delimited blocks without stripping the comments first.  Or, you can rewrite the low-level parser, which is at the moment not a good idea for me.  There is too high a risk to break somebody's syntax (it happened before in edge cases).

A possible solution may be splitting up the config string in `read_config_file()` or `read_config_string()` before stripping the comments, thus keeping a copy of each sub-string *including* comments.  Since you cannot use the actual parser yet, how about using the tags that I suggested earlier to split?  This would allow those functions to set aside a string that includes comments, to be then associated to the newly-created object (colvar or bias).

There may be a complication when dealing with `extra_conf`, but I assume that the Dashboard would only generate configuration consistent with the version of Colvars it uses.  And in any case Colvars can also prepend the same tag to any `extra_conf` segment it self-generates.  I think that having the tag generated may be useful for other reasons, such as detecting during parsing with which version of the Dashboard the config was generated.

The only real problem would be if someone edits the config file by hand without preserving the tags, then re-imports in the Dashboard.  Not sure how to handle that.

**Comment by jhenin** [comment]
A much broader consideration: would it make sense eventually to switch our config to YAML?
https://yaml.org/
That seems to be a very flexible, human-readable format, with good parsers.

**Comment by giacomofiorin** [comment]
There are indeed many YAML parsers around.  Which one do you propose to
use?

**Comment by jhenin** [comment]
I can't say I've explored the question fully, but this seems solid enough and well-maintained:
https://github.com/jbeder/yaml-cpp/

I'm not underestimating the cost of changing the file format. I'm just interested in a cost-benefit analysis over the medium term. The current structure of colvarparse is clean enough that YAML could be supported alongside the current format.

**Comment by giacomofiorin** [comment]
Absolutely yes. That's the whole purpose of encapsulating the lower level parsing code in its own class. 

I had not thought about YAML specifically, but it has caught on over the years and is definitely worth looking into. My main concern is that users should respect indentation, and errors deriving from wrong indentation may be more difficult to check than having an unbalanced brace count (for which there is a specific check now). This should definitely be a separate issue.

As you know, I'm currently dealing with proper scientific work that has piled up over time. In the near future for any parser-related work I'll try at most to finish supporting this issue to help improving the Dashboard more useful. I'd say that a YAML backend is definitely worth discussing, but after you get the Dashboard integrated.

**Comment by jhenin** [comment]
Finally I decided the path of least effort was to include a minimal amount of parsing in the Tcl plugin, see 2acf47189c5d46ce972fe915b162b6f3e5edd1e5.
