### ISSUE TITLE
Changelog for non backward-compatible changes

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#176]
Should be somewhere in the manuals, short. Could be used to update eg. NAMD tutorials. Reference in case something goes wrong.

-> lower/upperBoundary -> lower/upperWall
-> refPosGroup -> fittingGroup

**Comment by giacomofiorin** [comment]
This can be done quite quickly, also adopting the strategy of linking a URL together with a deprecation message (see my commit 69f3105 on the total force change).

What transpired from the Skype meeting with the NAMD people is that they would like to take "deprecation" more seriously than in the past, therefore the changes should be documented so that people can adjust.

The other side of the issue is that the tutorials *must* be updated by the respective authors within a reasonable time after being made aware of inconsistencies with the more recent code. Tutorials that are not updated should be taken offline for good: if they aren't, then the changelog would have to reach so far in the past to be more confusing than it's worth.
