### ISSUE TITLE
LAMMPS bias vector

### ISSUE THREAD

**Issue by alatham13** [Colvars/colvars#181]
Hello, we are working on developing our own vector collective variable component, which we would use to bias simulations. We would hope to use a vector for speed. As a test, we were looking at the distancePairs collective variable. Using LAMMPS, we were hoping to use the linear bias function to bias a distance pair. Yet, we get the following error:
Trying to assign a colvar value with type "scalar number" to one with type "n-dimensional vector".

Here is our input:
colvarsTrajFrequency    200
colvarsRestartFrequency 200
indexFile               groups.ndx

colvar {
name    pr1
distancePairs {
group1  { atomNumbers 1 2 3 }
group2  { atomNumbers 20 21 22 }
    }
}

linear {
name              max_ent
colvars           pr1
forceConstant    1
#centers       0 0 0 0 0 0 0 0 0
centers  (0, 0, 0, 0, 0, 0, 0, 0, 0)
outputEnergy      no
}

**Comment by jhenin** [comment]
Hi,

as it is written currently, the linear bias assumes it is dealing with scalar quantities. Accordingly, it treats the force constant as a scalar, and attempts to compute the biasing potential as k*(x - x0), expecting that to be a scalar, which it isn't. There should probably be a test in that bias to ensure the variables are scalar.

It could also be extended to work with vector variables. If you are willing to have a go at it, please do.

Best,
Jerome

**Comment by giacomofiorin** [comment]
Hi @jhenin I think in this case this qualifies as a bug fix, since when I integrated @whitead's old linear bias with the shared `colvarbias_restraint` base class I overlooked this particular case.  PR #182 should take care of it.

@alatham13 Please check that it works for your case as well, by running the `./update-colvars-code.sh` script (should work on the current `master` branch of https://github.com/lammps/lammps). If it works as expected, I can ask to merge this there as well.

The `linear` bias, just like the `harmonic` bias, will not use different force constants for each component of the vector variable.  To do so, and for the typical use case of applying experimental restraints on a vector variable (for example, a DEER time-signal) there is a new method called Restrained Average Dynamics (RAD) developed by @fabsugar coming out in Structure in a few days (authors: Marinelli and Fiorin).  When the manuscript comes out, I'll publish the code as well, and will add a comment to this issue as reminder.

**Comment by alatham13** [comment]
Perfect, your changes worked on the distancePairs. I think I implemented our code in a way where we get around that for our collective variable, but I will check out the Structure paper as well.
