### ISSUE TITLE
Split the cvc docs into subsections

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#200]
They are already ordered, but the different categories are not apparent.

**Comment by giacomofiorin** [comment]
Go ahead, but wait until #198 is merged?

**Comment by giacomofiorin** [comment]
#198 is merged, so you can work on `master` more safely.

Since the list extends for over a page of the PDF document, how about switching to alphabetical order for the list itself?  Ideally the doc for each CVC should also go alphabetically, but that's quite a bit of reshuffle so I'm not a fan.  Hyperlinks work anyway.

**Comment by jhenin** [comment]
The first part is done.

About the list: it is pretty much a copy of the TOC entries. If I were to improve the list, my best bet would be to format it into sections, just like the new TOC. Do we want that redundancy? Couldn't that section just refer to the TOC instead?

**Comment by giacomofiorin** [comment]
Sure, but in that case to feature alphabetical order you'd have to reshuffle the entire sections.  I'm not against it, but do keep in mind that the recent small addition by @alejob ran into merge conflicts already.

**Comment by giacomofiorin** [comment]
Never mind, I see that the sections grouped this way required minimal shuffling (of `cartesian` only).  At some point it may be useful to sort the variables alphabetically within each section but it is definitely not required now.

**Comment by giacomofiorin** [comment]
Closed by #205
