### ISSUE TITLE
Should we periodically write trajectory labels to file?

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#209]
Currently labels are written every 1000 steps in trajectory files. When processing the file with a script, this requires testing every single line for a hash, even when the config is known not to change. This makes what could be a one-liner script a little more complicated.

These labels is intended as a reminder to a human reader, but I'm not sure every 1000 lines is frequent enough to help a human reading a large file. I find it just as easy to refer to the first line.

I think we could write the labels only at the beginning of the file and upon config changes.

**Comment by jvermaas** [comment]
I'll be honest, I *also* only look at the top of the tile to find the titles, but I'm not sure how big of a difference it really makes. In python, numpy.loadtxt nicely already ignores "#" lines, and a "clean" file is pretty easy to get with just grep: 
> grep -v '^#' filename
Writing labels occasionally is consistent with how NAMD writes its logs, so it might just be my own biases for why I don't think this needs to be changed.

**Comment by giacomofiorin** [comment]
Having the labels periodically written allows you to look at the last few lines of a long file by using `tail`.

@jhenin If you think that 1000 lines is not frequent enough, just open a PR that changes it to 100.  You specifically can also push a commit directly to `master`, but for a change in behavior I'd like to have a PR (or at least to reference this issue in the commit message).  This is so that we can link this discussion in case someone's script breaks.

Moreover, I think that scripts that only check the first line for comments will break in those cases where the module is reinitialized during a run.  In NAMD, this happens in constant pH runs, to name an example of a recent feature.

Notably, the `plot_colvars_traj.py` script produces a clean text file as output, with variables listed in the order desired.  Sadly it doesn't use `numpy.loadtxt` (because it gets the variable names from the comments, so it can't ignore them!) and is hence quite a bit slower than a pure NumPy script, but I'm hoping that that can change in the future.

**Comment by jhenin** [comment]
The counter arguments are convincing enough. I'll pass along to users who gave the initial feedback.
