### ISSUE TITLE
componentCoeff and name not working with orientationAngle components

### ISSUE THREAD

**Issue by flblanc** [Colvars/colvars#213]
Dear developpers,

As of version 2018-12-20 (NAMD interface),  it seems that the keywords `name` and `componentCoeff`are not supported inside `orientationAngle`components, instead yielding the following error:

`colvars: Error: keyword "name" is not supported, or not recognized in this context.`

This notably precludes the usage of  `customFunction` with these CV components. Also, version 2017-07-15 of colvars does not exhibit the bug (I don't have a more recent version to test, sorry). Could you please investigate?

Thanks in advance,
Florian

**Comment by giacomofiorin** [comment]
Hi @flblanc this was introduced in #199: sorry about that.  The immediate fix is easy, but causes a error in the parser.  @jhenin I'd like to address this in the cleaned-up parser: if you are unable to review #196 immediately, I'll push the fix for this there without waiting for the merge into master.

**Comment by jhenin** [comment]
@giacomofiorin I'll review #196 in the next few hours.
