### ISSUE TITLE
Add example of moving frame of reference (DBC) to documentation

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#300]
Especially moving frame of reference. Also refer to the templates that ship with Dashboard.

**Comment by giacomofiorin** [comment]
This is reasonable, and I feel actually that the issue is pretty much reflecting what is already a choice for new or updated sections.  See the examples included in #261, #274, and #301.  The PDF of the manual is (in some version) 100 pages or longer: no point in saving space if an example can prove useful.

I feel like pointing out two things:
1. Snippets are always good. But long stretches of input fail to emphasize individual keywords well. It's best to use complete inputs *only* as templates for an input generator, and automate the user out of the process altogether. You do not need (and you should not think useful) to employ a PhD-trained scientist to do copy-and-paste.
2. Although there are some issues that have been open for long, why open one that is phrased in a way that is very unlikely to be closed?  Is there a point when there will be *enough* examples?

**Comment by jhenin** [comment]
> though there are some issues that have been open for long, why open one that is phrased in a way that is very unlikely to be closed? Is there a point when there will be enough examples?

Fair enough. I had something more specific in mind, so let me make the terms more specific.

**Comment by jhenin** [comment]
This is covered by the Dashboard template "DBC ligand RMSD", and by doc improvements.
