### ISSUE TITLE
Reflecting boundary conditions for extended Lagrangian

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#328]
Might bring a definitive solution to issues like #245 and #252

**Comment by fabsugar** [comment]
A similar issue at the boundaries is present in the case of metadynamics. In that case the problem is mostly solved using hills reflected at the boundaries. An even better solution but more cumbersome is to use inversion condition at the boundaries [https://journals.aps.org/pre/pdf/10.1103/PhysRevE.81.055701], the latter adjust not only the free energy value but also its gradient; however reflection seems to be sufficient in most cases.

**Comment by jhenin** [comment]
Thanks Fabio! As you see I've written the basic code. I need to test it with eABF.

**Comment by jhenin** [comment]
Closing this, now redundant with the PR #329 . Discussion can take place there.

**Comment by HanatoK** [comment]
@jhenin Although I remember this feature, I have to check the code for the actual option names. Could you please update the doc about the options accordingly?

**Comment by jhenin** [comment]
Thanks for the reminder!
434fa73a23abe9c8e3cd2cc3fc0751ba15ac61ba
