### ISSUE TITLE
colvarproxy base class has members that must be set by derived classes

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#365]
Working on the gromacs proxy we notived several cases of variables in colvarproxy that must be overridden by derived proxy classes. Some are pre-initialized to nonsensical values to force a later change (angstrom_value = 0.0) but others are just uninitialized (restart_frequency_engine).

One general mechanism to ensure that such variables are initialized is to hide them behind pure virtual accessors. Is that too cumbersome? Any other strategies?

A related question: should we track down and eliminate uninitialized data?

**Comment by giacomofiorin** [comment]
Pure virtual accessors sound good. Or even better, accessors that throw a `COLVARS_NOT_IMPLEMENTED` error (so that you don't *need* to reimplement them unless you use them). I tended to adopt the latter on newer methods that I added.

Indeed `restart_frequency_engine` should have been initialized to zero: it's the textbook example of a bugfix that introduces another bug. Commit 249ca251 fixes this.

Going over the members is a good idea for `colvarproxy`, which is a hodgepodge of things that should stay hidden from the rest of the library. The other classes mostly initialize stuff from input with a call to `get_keyval()`. I have progressively been replacing the hard-coded default value in calls to it to the *current* values of the parameter being initialized, and moved the hard-coded default to the constructor.

**Comment by giacomofiorin** [comment]
Note: I linked the repo with Coverity, which picks on several issues. One of these is unidentified parameters. Caveat: it can get quite verbose. I added your email as well. There are still a lot of calls to `get_keyval()` where the parameter is used uninitialized, because the call itself *is* the initializer. Moving the initialization to the constructor takes care of it.

**Comment by giacomofiorin** [comment]
Coverity gives this code a "passed" status, meaning the defects are medium or low priority. You should have also received a notification with a URL in it (if not, please let me know). The URL will give you a summary. Since I just registered this repo, we need to wait for a human to manually approve the open source character of the repository before you can wait for the individual defects. It looks better than the last time I looked at this report via the scan that @rbberger set up for LAMMPS. 
![image](https://user-images.githubusercontent.com/4512089/94282526-f05d4400-ff1d-11ea-948c-ed6173af371f.png)

**Comment by giacomofiorin** [comment]
The details of the scan are now accessible so I went ahead and silenced a few of them in 33da0c95 and re-ran the scan after it. Do you mind taking a look at the rest? It looks mostly like taking care of many harmless warnings to find the occasional bug.

If you need a new scan, I'm happy to rerun it. I prefer not to hook up a CI system like Travis just for this (certainly not while the Microsoftization of GH is still ongoing).

**Comment by jhenin** [comment]
Where can I find the coverity results?

**Comment by jhenin** [comment]
This issue will be taken care of over time using static analysis. Closing.
