### ISSUE TITLE
Support Lepton or other kinds of custom functions in GROMACS

### ISSUE THREAD

**Issue by HanatoK** [Colvars/colvars#388]
Currently Colvars can use neither lepton custom functions nor TCL scripting when integrating with GROMACS. Is there any way to easily implement a CV without hacking the C++ source of Colvars in GROMACS?
I take a look at PLUMED, and they bundle the lepton source code. Can Colvars do the same thing?

**Comment by giacomofiorin** [comment]
Hi, Lepton is definitely doable. @jhenin was looking into adapting the CMake recipe that I created for embedding Lepton in LAMMPS, but it should be relatively straightforward.

For Tcl, that would involve a bit of a discussion with the Gromacs devs. We strive to keep the same build system and do not add significant dependencies. They seem to have enough work set already with Python/gmxapi at the moment, which arguably will be much more useful than Tcl when it builds consistently on all current platforms without needing too many tweaks :-)

Since you took a look, can you confirm that the Lepton version bundled with Plumed is now the official version without local changes?

**Comment by HanatoK** [comment]
@giacomofiorin 
No, PLUMED extended a few inverse hyperbolic functions. I proposed to merge those extensions to openmm's repository in #231 , but only atan2 was added back.

**Comment by HanatoK** [comment]
@giacomofiorin 
No, PLUMED extended a few inverse hyperbolic functions. I proposed to merge those extensions to openmm's repository in #231 , but only atan2 was added back.

**Comment by jhenin** [comment]
Yes I looked into adding Lepton, but I'm a beginner with CMake, so that was harder than I thought. There's also the question of proposing a directory structure that will be acceptable to Gromacs folks, so there were tough choices to make. I think we need to talk to gmx developers about it first. We'll do it asap and get back to you.

**Comment by giacomofiorin** [comment]
@HubLot @jhenin If you want to take a stab at this, I would suggest trying with a build system where Lepton is downloaded externally (via the OpenMM repository as we have in the Actions) and then linked to GROMACS. This would avoid the issue of where to place it, although in my opinion `src/external` is a good enough place for our own patched releases.

Given that Lepton is small enough that you can also build it easily with CMake, check out out how this is done in LAMMPS, e.g. `cmake/Modules/Packages/MDI.cmake` for a recent example.

After the holiday, I can also take a closer look.

**Comment by HanatoK** [comment]
I take a look at the source code of GROMACS and they are indeed using muparser for pulling. However, they use numerical differentiation instead of symbolic differentiation in lepton. Do you have any idea about why muparser and numerical differentiation are selected?

**Comment by giacomofiorin** [comment]
For completeness here are earlier messages about muparser, which are more appropriate to have in this conversation (especially after the last comment):
https://github.com/Colvars/colvars/pull/444#discussion_r796800360

Replying to the last comment: I have no idea why they picked muparser instead of Lepton. @jhenin and I didn't know about Lepton until seeing a presentation by its author (Peter Eastman), but it was [fairly easy to add](https://github.com/Colvars/colvars/commit/792addd124e63116a1e24f1e6a0e34ac111b10c9). PLUMED started using it [immediately after](https://github.com/plumed/plumed2/commit/a4ce7f8889d6c3506ba40b702418c5695226a7bb).

We're practically already embedding Lepton, at least in LAMMPS (look at the CMake recipe for Colvars there). The same could be done in GROMACS, or Lepton could have its own CMake recipe. Either would work.

But VMD and CMake? Seriously?

**Comment by HanatoK** [comment]
> For completeness here are earlier messages about muparser, which are more appropriate to have in this conversation (especially after the last comment): [#444 (comment)](https://github.com/Colvars/colvars/pull/444#discussion_r796800360)
> 
> Replying to the last comment: I have no idea why they picked muparser instead of Lepton. @jhenin and I didn't know about Lepton until seeing a presentation by its author (Peter Eastman), but it was [fairly easy to add](https://github.com/Colvars/colvars/commit/792addd124e63116a1e24f1e6a0e34ac111b10c9). PLUMED started using it [immediately after](https://github.com/plumed/plumed2/commit/a4ce7f8889d6c3506ba40b702418c5695226a7bb).
> 
> We're practically already embedding Lepton, at least in LAMMPS (look at the CMake recipe for Colvars there). The same could be done in GROMACS, or Lepton could have its own CMake recipe. Either would work.
> 
> But VMD and CMake? Seriously?

NAMD bundles Lepton without CMake. Is it possible to do the same in VMD? Another option may be distributing Lepton source files within Colvars (and without CMake), and PLUMED has done the similar thing.

**Comment by jhenin** [comment]
> Another option may be distributing Lepton source files within Colvars (and without CMake)

I'm in favor of that in principle. VMD sources can be patched with Lepton and compiled using GNU make - we do that internally, but getting those files accepted into the main VMD tree is difficult. For Gromacs, we need discuss it with the main developers.

**Comment by giacomofiorin** [comment]
I found this discussion:
https://gitlab.com/gromacs/gromacs/-/issues/3515
and in particular this post about Lepton:
https://gitlab.com/gromacs/gromacs/-/issues/3515#note_377286688
where according to the person who added the feature in GROMACS switching to Lepton wouldn't be difficult.

To be clear, bundling with CMake, traditional make, etc are all good with Lepton, but the build system needs to support building source codes from more than one folder. All codes do, except VMD: for that, the [patch](https://github.com/giacomofiorin/vmd-patches/tree/master/lepton) I wrote links Lepton as an external library, to be built before VMD. So even that is not an issue. The only issue with VMD/Lepton is convincing John to accept that patch. The best approach would be contacting him directly: @jhenin and I already tried.

For GROMACS, the resistance against importing it may not be as strong, but likewise more lobbying with [them](https://gitlab.com/gromacs/gromacs/-/issues/3357) would be useful. Meanwhile, it is not difficult at all to include Lepton in our own patched GROMACS releases. Can we wait for @HubLot to chip in?

**Comment by giacomofiorin** [comment]
@HanatoK Please check #461, there is a link to a working branch of GROMACS 2021.

**Comment by HanatoK** [comment]
@giacomofiorin I can confirm the code works for GROMACS 2021.3 (both compilation and running).

**Comment by giacomofiorin** [comment]
Solved by #461
