### ISSUE TITLE
Add a citation file

### ISSUE THREAD

**Issue by sroet** [Colvars/colvars#421]
I saw a presentation about this software from @jhenin, which led me to this repo.

One thing I quickly noticed is this repo does not yet has a [citation file](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files), which helps github to quicky export a (bibtex/apa) citation for this software

Feel free to close this issue if you don't want to use this functionality

**Comment by jhenin** [comment]
Thank you @sroet , will look into this!

**Comment by jhenin** [comment]
Done.

**Comment by giacomofiorin** [comment]
Thanks @sroet for pointing this out and @jhenin for uploading the record.

It is worth noting that our Mol Phys 2013 describes the overall framework and the features included at the time. Other parts of this software are described in other papers, which are cited in the documentation and in the most recent version are also printed to the log/screen when the corresponding features are used (since #419).
