### ISSUE TITLE
Conflicts in doc when merging branches

### ISSUE THREAD

**Issue by giacomofiorin** [colvars/colvars#44]
The issue is much milder than a few months ago (when we had separate html files), however htlatex often generates extensive changes to the HTML documentation corresponding to tiny changes in the actual source.  Aside from inflating the size of commits (which is harmless), merging is a bit more difficult.

Solution A: we move doc and examples to a separate sub-repository.
Solution B: we just don't document stuff until it gets into the master branch.

**Comment by agrossfield** [comment]
Alternatively, you could remove the html from the reository, and treat it as something that is built rather than as a piece of the source.

Dr. Alan Grossfield
Department of Biochemistry and Biophysics
University of Rochester Medical Center

On Sep 24, 2015, at 7:20 PM, Giacomo Fiorin <notifications@github.com<mailto:notifications@github.com>> wrote:


The issue is much milder than a few months ago (when we had separate html files), however htlatex often generates extensive changes to the HTML documentation corresponding to tiny changes in the actual source. Aside from inflating the size of commits (which is harmless), merging is a bit more difficult.

Solution A: we move doc and examples to a separate sub-repository.
Solution B: we just don't document stuff until it gets into the master branch.

-

**Comment by jhenin** [comment]
You're right, I should have done that when I added the html docs to the
github.io page. I did that mostly to have them indexed by search engines.

The convention would be: each branch contains the relevant doc as latex
sources, and the github.io pages document the current master branch in PDF
and HTML form.

**Comment by jhenin** [comment]
Should be solved by today's commits. On top of it, I am hoping that the HTML docs will be well-indexed by search engines now.
