### ISSUE TITLE
Visualize restraints as vector fields(?)

### ISSUE THREAD

**Issue by EzryStIago** [Colvars/colvars#446]
I know it is possible to visualize gradients and, in a given simulation frame, the restraint field can be visualized by manually probing the system. Would/will it be possible to visualize the entire restraint as a vector field simultaneously? This would make it easier (especially for new users) to get visual feedback while designing a set of (simple, geometric) restraints. I do realize more complex restraints like rmsd or even dihedral restraints may be more difficult to visualize as a vector field.

**Comment by giacomofiorin** [comment]
I'm not sure what you mean by "manually probing", so it's hard to tell exactly what's the feature that you're looking for either.

In general terms, what you describe is a typical use case for the Colvars Dashboard, which you can get from here or pre-built with VMD 1.9.4 (which is better, because the Dashboard requires also updates to Colvars itself that VMD 1.9.3 didn't have).
https://arxiv.org/abs/2110.08758
https://colvars.github.io/colvars-refman-vmd/colvars-refman-vmd.html#sec:dashboard

@jhenin will eventually post a tutorial for the Dashboard itself, but the gradient display feature is already used in this one:
http://colvars.github.io/multi-map/multi-map.html

**Comment by jhenin** [comment]
I can see how this could be done if the restraint depended on, say, the Cartesian coordinates of a single atom. Then the force could be visualized as an R^3->R^3 mapping - maybe just as 2d slices. But that would not be much of a collective variable, and I can't see how that generalizes to anything more collective, because of the high-dimension spaces involved.

**Comment by EzryStIago** [comment]
Dr. Fiorin: By "manually probing" I just mean manually moving the selected atoms in vmd and looking at the corresponding colvar value.
Dr. Henin: I certainly see your point - this kind of visualization (before simulation) would not be useful for anything more complicated than harmonic walls. I still need a way to validate my restraints before simulation, but I could also do that with existing tools in VMD.
