### ISSUE TITLE
Issue with Eigenvector CV units in GROMACS when vector is declared from .xyz file

### ISSUE THREAD

**Issue by flblanc** [Colvars/colvars#471]
Dear colvars devs,

I have encountered a possible unit-related bug. When using an eigenvector CV with GROMACS, I get values that are 10 times lower than they should be. 
I am aware that in GROMACS the projection onto an eigenvector will be expressed in nm; what I mean here is that the value returned by GROMACS/colvars is 100 times smaller than the value computed in Angstroms by an independent program (whereas it should only be 10 times smaller). 

I am using a .xyz file to declare the coordinates of the eigenvector (with vectorFile). According to the manual, .xyz files are always considered to be in Angstroms. Therefore I think what happens is that the entries of this .xyz are assumed to be in Angstroms and are rescaled (divided by 10) by GROMACS. If so, this is a bug, because after this rescaling the norm of the eigenvector will no longer be equal to 1. As a fix, one could either remove this rescaling specifically for eigenvector CVs, or perhaps add an automatic normalization step for the eigenvector. 

Another remark: in the file `colvarcomp_distances.cpp`, line 1406, the instruction:

`cvm::log("The norm of the vector is |v| = "+cvm::to_str(eigenvec_invnorm2)+".\n");`

prints, as far as I understand, the inverse of the vector square norm (1/|v|²) rather than |v|. This is harmless with normalized vectors because all these numbers are equal to 1. But in my case, I obtain: 
`The norm of the vector is |v| = 100.73.` 

from the colvars log, which is consistent with the norm of my vector now being (approximately) 0.1 instead of 1 (1/0.1² = 100). 

Could you please investigate? I observed the bug in Gromacs-2021.5 with colvars version Feb9-2022 and Feb20-2022. 
Thank you very much ! 
Florian

**Comment by giacomofiorin** [comment]
Hi @flblanc thanks for bringing this up! Indeed it looks like this particular use case was overlooked in #295. I don't think that there can be a fix that is both quick and robust without annotating the XYZ file in some way, because if the contents are coordinates the unit conversion is clear, because they have length units. But for eigenvector components the conversion would be entirely different because they could have no unit, or have a unit of *1/length*. So with the code structure as it is, I don't see an easy way to reuse the same `vectorFile` in both VMD and GROMACS, for instance.

Until we figure out a consistent way to handle this, these are three realistic workarounds that I can see:

1) Without changing the contents of the XYZ file (which would be tedious, but you could go that way if you wish), do the unit conversion at the level of the CVC, i.e. in the `eigenvector` function's definition use the [`componentCoeff` keyword](https://colvars.github.io/colvars-refman-gromacs/colvars-refman-gromacs.html#sec:cvc_superp):
```
eigenvector {
    componentCoeff 10.0  # Correct for mistaken unit conversion
    vectorFile file.xyz
    ...
}
```

2) In the special case that your vector components are the differences between coordinates of two structures A and B, use the `differenceVector` flag and just pass the coordinates to the "B" structure to Colvars, so that the normalization can be done internally, in *consistent* units:
https://colvars.github.io/colvars-refman-gromacs/colvars-refman-gromacs.html#sec:cvc_eigenvector
In this special case only, the Colvars config would also be portable to other codes and it would be the best solution.

3) If neither of the above works, embed the vector components directly in the Colvars config, so that they are read as "raw" numbers and are expressed in the same units of GROMACS, i.e. nm. This would require using `vector` instead of `vectorFile`, and be written like this:
```
vector {
(x1, y1, z1)
(x2, y2, z2)
...
(xN, yN, zN)
}
```
and a quick way of generating the right format if you have the vectors stored as a NumPy array would be:
```
for i in range(vectors.shape[0]):
    print(tuple(vectors[i,:]))
```

**Comment by giacomofiorin** [comment]
P.S. I forgot to mention that I updated the reported `|v|`, using the more complete formula in the message to be sure of what is being printed: https://github.com/Colvars/colvars/commit/35f2545734a76c0cb7137dd74a75f4f3169a5284

**Comment by flblanc** [comment]
Thanks @giacomofiorin for these solutions! I had prepared a new .xyz with scaled up entries, but the `componentCoeff` approach you suggest seems to me the easiest (and corresponds to my use case of projecting onto an eigenmode rather than a difference vector). Perhaps, it could be added as a remark in the manual? Something like: 


\textbf{Using VectorFile with .xyz file} In GROMACS, when the eigenvector is declared with VectorFile using a .xyz file, the entries of the file will be considered as \AA and rescaled to nm. If the eigenvector had been normalized to unit-norm beforehand, this will result in the value of the CV being 10 times lower than expected. To correct for this behaviour, one can use `componentCoeff`: 

```
eigenvector {
    componentCoeff 10.0  # Correct for mistaken unit conversion
    vectorFile file.xyz
    ...
}
```

**Comment by jhenin** [comment]
Thanks @flblanc for the report, and for the suggestion to update the documentation.

I see two possible fixes, which are not mutually exclusive:
- add an option to normalize the vectors after reading (off by default);
- tell the XYZ file parser to read in raw numbers (unitless) instead of coordinates (with unit translation). This can be done cleanly by adding a "raw" mode to `load_coords` (this would be on by default in eigenvector).

**Comment by giacomofiorin** [comment]
Note that the normalization method would also be different depending on the value of `differenceVector`, i.e. the vector would be normalized to 1 in the case of a PCA-based CV, which would retain length units. But the _value_ of the CV would still be normalized to unity when computed between the endpoint structures with `differenceVector yes`.
