### ISSUE TITLE
pABF documentation

### ISSUE THREAD

**Issue by HanatoK** [Colvars/colvars#473]
It seems I cannot find the documentation of projected ABF options, namely `integrate`, `integrateMaxIterations`, `integrateTol` and `pABF*`. Could @jhenin add documentation for them?

**Comment by jhenin** [comment]
For context : this was intentional, in the sense that my tests didn't indicate significant benefits to using pABF (see the JCTC paper on integration), so it is in the code merely for experimental purposes. I didn't want to encourage its usage for any particular purpose.

That said, I agree that as a matter of principle, anything that is in the code should be documented, so I will do that while warning about the limited benefits, if any.

**Comment by jhenin** [comment]
Ah I see. I misunderstood because pABF is disabled by default, but integration is enabled to allow for free energy output. Yes, these should absolutely be documented, this is an oversight on my part.

**Comment by HanatoK** [comment]
@jhenin A quick question: if I do not enable pABF, which option should I used to control the frequency of integration? Is that the same as `pABFintegrateFreq`?

**Comment by jhenin** [comment]
Integration happens at every gradient/free energy output. So you can either use integrate off or reduce the output frequency.
