### ISSUE TITLE
Implement minimum image distance RMSD

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#477]
This is necessary when using the `fittingGroup` option, which does not guarantee that current coordinates are closer to the reference than the half periodic cell size. See in particular the case of the DBC coordinate.
This could be the default when `fittingGroup` is active, and disabled by `forceNoPBC` to generalize other distance functions.

**Comment by jhenin** [comment]
Cannot be done for now, because it requires applying PBC in a rotated frame of reference.

**Comment by giacomofiorin** [comment]
> Cannot be done for now, because it requires applying PBC in a rotated frame of reference.

Yup! Alternatively, how about having a setting that exits with error when the minimum-image condition cannot be satisfied safely?

**Comment by jhenin** [comment]
That would be good. I'm not sure what criterion to use for this.

I can see two ways to solve the initial problem:
1. implement rotated minimum image distance computation;
2. implement PBC wrapping of coordinates around the reference center before performing the rotational fit.

Neither is very simple, but the second is a little lighter I think.

**Comment by giacomofiorin** [comment]
Well, now it gets interesting. In the old days we had more or less option 2 already in place (i.e. PBC wrapping of all atoms around the first atom); the function was called `select_closest_image()`. 

Unfortunately, using that function led to issues with groups that span more than half the cell, even when these are treated correctly by the MD engine (e.g. a very large protein bond-connected throughout). I found an old email thread with Chris Chipot and JC Gumbart related to this. I had originally put that provision in the pre-Colvars code, intending to support both GROMACS and NAMD, but you convinced me it was much safer to just stop using `select_closest_image()`, because NAMD maintains sets of unwrapped coordinates in a consistent manner (and indeed it has worked okay).

If you see a risk that, despite the user's best efforts, wrapping could lead to incorrect results, my thought in the comment above was not to blindly wrapping again with `select_closest_image()`, but rather compute the shift first and raise an error if it exceeds half the unit cell dimension. To me this is an issue already when computing a center of mass/geometry, and the check should be done there. If the coordinates and their center of mass are consistent, it is straightforward to compute the rotation afterwards with the existing code.

Essentially have alternative options like:
1. I know that my atoms will always stay nearby, wrapping or no wrapping => no need to worry about PBCs.
2. I don't know that the above will be true, so I want the code to warn me when it isn't => exit the code.
3. I know what I'm doing and defining a wrapping center is sufficient for my case => use a revived `select_closest_image()`.

**Comment by jhenin** [comment]
Ah yes, I found the email thread from 2009!

I came across this again not even because of Gromacs, but because of NAMD users who enabled wrapAll. Not something I ever do, but it's difficult to forbid it entirely.

I think the set of 3 options that you propose would cover everything pretty well.

**Comment by zwpku** [comment]
I came across this issue when I looked for causes of apparently incorect results that I obtained from an ABF simulation of a protein in Gromacs, where I took RMSD as a colvar. It turned out that the problem I had was due to the use of an initial configuration whose atoms cross the PBCs.  This may break the calculation, as pointed out in Section 3.2 of the ColVars manual for Gromacs.   

Concerning the issue discussed here, especially the three options above, I am thinking about the scenario where I want to compute the RSMD wrt a folded reference in an ABF simulation. The box size is large enough for major configurations of interest, but the end-to-end distance of protein may exceed half of the box size when the protein becomes unfolded. In this case I think no wrapping (1st option) shall still give correct RMSD when the system is unfolded (e.g. RMSD defined using atom groups in the two-ends), exiting (2nd option) would give indication that the box is not large enough, whereas wrapping (3rd option) will underestimate the RMSD? 

I found the discussions in #11 helpful to understand the details.

**Comment by jhenin** [comment]
> In this case I think no wrapping (1st option) shall still give correct RMSD when the system is unfolded (e.g. RMSD defined using atom groups in the two-ends), exiting (2nd option) would give indication that the box is not large enough, whereas wrapping (3rd option) will underestimate the RMSD. Is this correct?

That seems correct. Our recommended approach so far is to provide a starting point that defines the correct relative arrangement of atoms, and Colvars takes it from there. I have yet to see a case where that can't work at all, but it is dependent on some properties of the initial configuration that are under the user's control. I agree with Giacomo's idea to have a check for groups that are too extended. Since users ignore warnings as a rule, that could be an error condition that can be disabled by an explicit keyword "allowScatteredAtoms" or something in that spirit.

**Comment by giacomofiorin** [comment]
Thanks @zwpku for reopening, it would have probably stayed forgotten.

**Comment by zwpku** [comment]
Thanks @jhenin for providing further information. I think it's clear to me and I can close this issue again.
