### ISSUE TITLE
NAMD interface test 003_reinitatoms fails

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#501]
NAMD 2.13 passes. NAMD 2.14 gives a segfault, and the devel version : "corrupted double-linked list".

This is afaik a rarely-used feature.

**Comment by jhenin** [comment]
Related: how do we make sure NAMD interface tests are run regularly? Maybe run them in CI only when `colvarproxy` or `colvarproxy_namd` changes?

**Comment by giacomofiorin** [comment]
That test occasionally fails, and given how many dusty corners of NAMD are being exposed by reinitatoms, the chances that this is due to Colvars are not high.

I'd keep an eye out for people mentioning sporadic errors in constant pH, although whatever race condition is there may not even show up for larger systems.

**Comment by jhenin** [comment]
I have checked that this only happens when parsing a Colvars config after reinitatoms.
If I rebuild in debug mode, the segfault disappears. Neat.

**Comment by jhenin** [comment]
Fixed by #537
