### ISSUE TITLE
Allow lowerWall > upperWall for periodic CVs ?

### ISSUE THREAD

**Issue by jhenin** [Colvars/colvars#511]
I wonder if this test 
https://github.com/Colvars/colvars/blob/0b9078e68e244019198895d9c889383459b8dd8c/src/colvarbias_restraint.cpp#L979
could be relaxed for periodic CVs. I have a user who wants her periodic CV (distanceZ) held higher than x OR lower than -x, with x>0.

**Comment by giacomofiorin** [comment]
Can she use `wrapAround`, so that the values can still be monotonic?

I.e. set `wrapAround` to L/2, then you can have `lowerWalls` equal to (L/2 - x) and `upperWalls` to (L/2 + x)?

**Comment by jhenin** [comment]
That should work, but i'm a little worried about edge effects with box fluctuations in NPT since the period has to be set manually.

**Comment by giacomofiorin** [comment]
If the box fluctuations are smaller than the number you indicate as x, then it should be okay. Otherwise, I don't think that restructuring the code would help anyway.

A safer but also more broadly useful approach may be an alternative implementation of `distanceZ` in fractional coordinates. That would also require accounting for new contributions to the virial, though. I have tried to avoid that change so far for volumetric map variables, but there are use cases where it would make a lot of sense.

**Comment by jhenin** [comment]
Thanks for the input. Since there is no short-term actionable item, I'll close this for now.
