### ISSUE TITLE
Changing bias temperature during restart in WT-MetaD

### ISSUE THREAD

**Issue by Praveen-2k21** [Colvars/colvars#517]
Hi all, 

I am running a WT-Metadynamics of a solute in a membrane with a hill height of 0.07 kcal/mol and bias temperature 2750 K. While I was able to successfully run it for 800 ns, now I am getting an error that atoms in the system are moving too fast and I am pasting the exact error below, 

ERROR: Atoms moving too fast; simulation has become unstable (3 atoms on patch 32 pe 19).
FATAL ERROR: Low global CUDA exclusion count!  (69661 vs 69663)  System unstable or pairlistdist or cutoff too small.

I tried increasing pairlistdist but I am getting same error. 

Now I would like to restart the simulation from the point it crashed, my query is 

i) my idea is to use a lower bias temperature during the restart so that I can avoid this instability. Is it advisable to do so? will this be accounted for in the PMF output files?   

Best, 
Praveen

**Comment by giacomofiorin** [comment]
The NAMD message says "system unstable _or_ pairlistdist or cutoff too small", and in this case it's likely the former.

It's hard to guess what the precise problem is from a brief description. I can only recommend to first troubleshoot the definition of the CV, so that (1) indeed you no longer have issues related to PBC wrapping, and (2) the CV is a fair reaction coordinate in the sense that the molecular system responds well to applied forces. Check the atomistic trajectory throughout the simulation, and for example using VMD and the Dashboard.

Alternatively you could do a SMD simulation not to get a PMF (it is unlikely to be a great alternative for this) but rather to make sure that the CV is well defined whichever configuration you are simulating.

**Comment by Praveen-2k21** [comment]
Thank you Giacomo, 

I will check if the CV is optimized using the method you had mentioned. 

Along the same lines, I wanted to ask about two other parameters (colvar width and hill width). 

My CV space is 90 Angstrom (-45 to 45 Angstrom), currently my colvar width is 0.1 Angstrom and hillwidth 2 Angstrom, and I also read from the manual that "the width of each Gaussian hill  is given by the product between this hillwidth and the colvar's width.
So this means that the width of the Gaussian hill is 0.2 (2*0.1) Angstrom (Please correct me if I am not interpreting this correctly). 
So for the entire CV Space of 90 Angstrom the hills will be added with a width 0.2. My query is if my choice of hillwidth and colvar width realistic? I can notice that my PMFs are very smooth and at the same time it is taking very long to converge. 

I sincerely thank for all the advice you have given me  :)

best, 
praveen

**Comment by giacomofiorin** [comment]
I didn't see at first the question about the width of the Gaussian hill. Yes, you read the manual correctly. Note also that you can use [[gaussianSigmas]](http://colvars.github.io/colvars-refman-namd/colvars-refman-namd.html#sec:colvarbias_meta_basics) if you want to give that parameter directly (of course, the `width` of the grid bins should be appropriately larger).

The question about convergence should be answered by somebody involved in your project.
