### ISSUE TITLE
colvarproxy::post_run() & restart output filename

### ISSUE THREAD

**Issue by HubLot** [Colvars/colvars#534]
Hi,

It seems to me that the function colvarproxy::post_run() doesn't use the correct restart filename (colvars.state).
This function use:
```c++
error_code |= colvars->write_restart_file(cvm::output_prefix()+".colvars.state");
```
to write the state file.

But there is a specific string dedicated to the state filename called `restart_out_name` set in `colvarmodule::setup_output()`.
This is string is not used in the `post_run()` above so we cannot change specifically the state filename in the proxy.

**Comment by giacomofiorin** [comment]
Thanks. This is more an issue of:
1. unclear naming, because `write_restart_file()` is used both to write a "checkpoint" file mid-computation and the "final output" file that only gets written at the end of the designated number of steps
2. inconsistent placement, because the first of the two use cases is in the `colvarmodule` class:
https://github.com/Colvars/colvars/blob/60f6bc42168c9180efc3ffe90d562e6659556e96/src/colvarmodule.cpp#L796-L801
but the other is the one you are pointing at, in the `colvarproxy` class.  In NAMD and LAMMPS, the "checkpoint" is optional whereas a "final output" is required.

If this is incompatible with how the MDModules in GROMACS are expected to write their state, it certainly could be changed.  I'm not 100% sure how, though.

The long-term expectation by the GROMACS team is that most people would "run" for an indefinite number of steps, hit the walltime and use the latest checkpoint to resume it.  In this use case, the "final output" is never written.  However, there are still a lot of people who run each job to its completion.

Can you expand on the context where how `post_run()` is written became a problem?

**Comment by jhenin** [comment]
About Giacomo's first point, I suggest renaming the function `write_state_file`.
About the second point: while not ideal for consistency, there is some logic in having the proxy take care of `post_run`, as it has access to more information on when the run ends. That said, ideally, `post_run` would be part of the module, possibly triggered by the proxy.

**Comment by HubLot** [comment]
Thanks for the clarification @giacomofiorin.
The issue here is unrelated to GROMACS state/checkpoint, it concerns the `post_run()` function.

From what I understand, this function must be called by the proxy at the end of the simulation to write the "final" output & restart files (2nd use case). In the case of GROMACS-MdModule version, `post_run()` is always called because it is part of the proxy destructor (which is always called even with a ctrl+c). (For the others versions, `post_run()` isn't used *per se* but i'm using a similar function).

The point here is that the chunk of code you copy/paste @giacomofiorin should be used also in the `post_run()` function to take the `restart_out_name` variable into account.

**Comment by HubLot** [comment]
@jhenin and I had a discussion about this issue and NAMD file ecosystem. I didn't realized that NAMD had "intermediate" files (called restart) and "final" files (called output) and that the differences of writing between `calc()` and `post_run()`  came from this specificity (in GROMACS, intermediate files like state file are overwritten once the MD is finished).
And I didn't realized that `restart_out_name` is for those "intermediate" files and not the "final" ones.

Now I understand, I think we can close the issue.
