### ISSUE TITLE
Incorrect RMSD when using "run 0" then "cv configfile" and then "run N" in NAMD

### ISSUE THREAD

**Issue by HanatoK** [Colvars/colvars#536]
Hi! I am using NAMD by script running with Colvars, but the RMSD seems wrong. My Colvars configuration is
```
colvarsTrajFrequency 10
colvarsRestartFrequency 5000
indexFile alad.ndx
smp off

colvar {
  name dihedral_A
  dihedral {
    group1 {atomNumbers {5}}
    group2 {atomNumbers {7}}
    group3 {atomNumbers {9}}
    group4 {atomNumbers {15}}
  }
}

colvar {
  name dihedral_B
  dihedral {
    group1 {atomNumbers {7}}
    group2 {atomNumbers {9}}
    group3 {atomNumbers {15}}
    group4 {atomNumbers {17}}
  }
}

colvar {
    name rmsd
    rmsd {
        atoms {
            indexGroup Atoms
        }
        refPositionsFile ref.xyz
    }
}
```

I use the following commands in the NAMD input file :
```
colvars                 on

firsttimestep		0
run			0

cv configfile rmsd.in
run 40
```

But then the Colvars traj file is incorrect:
```
# step       
           0 
# step         dihedral_A             dihedral_B             rmsd                 
           0   -8.25111514934035e+01   7.82878040124970e+01   1.52341358796618e+00
          10   -8.13773511440876e+01   7.37152755486682e+01   1.52341358796618e+00
          20   -7.98939764048137e+01   7.21838555446005e+01   1.52341358796618e+00
          30   -7.80847181113126e+01   

7.41707606870538e+01   1.52341358796618e+00
          40   -7.63721010622145e+01   7.74879983813807e+01   1.52341358796618e+00
```
The rmsd column is incorrect and never updated. Any ideas?

The test file is attached.
[test_colvars_rmsd.tar.gz](https://github.com/Colvars/colvars/files/11663139/test_colvars_rmsd.tar.gz)

**Comment by giacomofiorin** [comment]
@HanatoK Thanks for the example input and report! I can reproduce the bug also with NAMD versions 2.12 through 2.14. 

The bug lies in how the map between the NAMD topology and the internal indices is initialized. This looks like an edge case where the logic that triggers the map's reinitialization breaks. Unfortunately, this logic is a bit complicated because it needs to handle also cases where GlobalMaster-derived objects other than `colvarproxy_namd` request atoms of their own.

I found that a safe way of preventing this error is to update the map's entry on the spot whenever a new atom is requested. Opening a PR with the fix now.
