### ISSUE TITLE
Turn walls into a separate bias

### ISSUE THREAD

**Issue by jhenin** [colvars/colvars#58]
Caveat: extended-Lagrangian colvars, where we want the walls to be applied to the actual coordinate.

More generally, we'll probably need a mechanism for applying biases either to the extended DOF, or to the geometric coordinate "actual value".

**Comment by jhenin** [comment]
The specific problem of extended Lagrangian is solved by commit d7907a0 that makes walls behave like any other bias again.

**Comment by giacomofiorin** [comment]
Excellent.  Mostly I'd like to move on to flat-bottom harmonic potentials to allow changing the force constant over time (i.e. allow the NMR simulated annealing protocol) or the centers/boundaries.

**Comment by giacomofiorin** [comment]
Done by 31c803b633c01baac3824f34e4c37b89e1231f2d

**Comment by jhenin** [comment]
Last step, which should be simple, to make this new bias replace the current walls entirely: let biases apply colvar forces that bypass the possible extended Lagrangian coordinate, and are applied to the geometric colvar.

**Comment by giacomofiorin** [comment]
Ah yes, the special treatment of the EL case by the walls...  Commit f561b6 (a one-liner, btw) should take care of this.

Since we're being nitpicky, let's keep it open until after I add code to handle the backward-compatibility with the old syntax. When the colvar object being initialized finds walls-related kewyords, it should pass back to the colvarmodule a config string that creates a corresponding walls bias.

**Comment by giacomofiorin** [comment]
Fixed by 4d02487
