### ISSUE TITLE
Which OS to build documentation on?

### ISSUE THREAD

**Issue by giacomofiorin** [Colvars/colvars#580]
Given that the container image for building the doc is quite big, I'd like to merge its role with those used to build the library code and the backends.

Sadly, RHEL-like OSs don't really offer a great variety of LaTeX packages (unlike Fedora).

To get a LTS software stack, I've tried with Ubuntu 22.04 using the packages shown below, but I had some issues with some MathJax formulas failing to render for some reason. No such issue with Fedora.  I'm curious whether anybody has the doc build working on a recent Ubuntu? Thanks!
```
sudo apt -y install texlive-latex-base texlive-fonts-extra latexmk doxygen 
python3 -m pip install bs4 html5lib lxml
```

**Comment by zwpku** [comment]
@giacomofiorin some tests on my Ubuntu 20.04. 

- There are some issues with the subscripts in the html:   
![original](https://github.com/Colvars/colvars/assets/41971527/7330122f-165d-4c1e-b559-494f0a3ebf2f)

- After adding curly braces to the corresponding equations in the tex file, e.g. \mathrm{x}\_{i}  -> {\mathrm{x}}\_{i}, the output becomes
![bracket](https://github.com/Colvars/colvars/assets/41971527/2e4b0b1a-160a-4d30-a61b-c3c50d812ca4)

    The subscripts are correctly displayed, although there seems to be a larger space between the subscripts and the following bracket $(t)$. 

- Without modifying the tex file, I tried to generate html using make4ht instead of htlatex, i.e. 
`
   make4ht colvars-refman-namd.tex "html5mjlatex.cfg, charset=utf-8" " -cunihtf -utf8" "-doutput/path"
`
The output is:
![make4ht](https://github.com/Colvars/colvars/assets/41971527/8f3b3399-1caf-4a61-bae2-a8ce984bfd46)

**Comment by giacomofiorin** [comment]
@zwpku Thanks so much for looking this!

I tested make4ht (which fortunately is available via a Ubuntu package) locally, and I can confirm that the formula gets rendered as a picture, not as MathML code. Is that the same in your case? I used the same command line as you, except for `-doutput/path` that simply changes the work directory.

**Comment by zwpku** [comment]
@giacomofiorin The formula is rendered as a picture in my case as well.  Adding mathjax to the command line, i.e. 
`
      make4ht colvars-refman-namd.tex "html5mjlatex.cfg, mathjax, charset=utf-8" " -cunihtf -utf8" "-doutput/path"
`
gives MathML code (I simply followed the commands on the [tex4ht webpage](https://tug.org/tex4ht/)) . The formulas in the rmsd section are correct, but in my case all the bold symbols using \bm are not rendered.

**Comment by giacomofiorin** [comment]
Closing for now, because containers are now better supported by GitHub and generating a new Fedora container to replace the current one is straightforward.
