### ISSUE TITLE
Parser improvements

### ISSUE THREAD

**Issue by giacomofiorin** [Colvars/colvars#68]
There is a need for a new mode `parse_required`: the value of the keyword must be provided, and the default value should never be used (some initializers, and all restart reads). The new mode should remove the need for the numerous calls of the type:
`cvm::error("Error: xxyyzz is missing from the restart.\n")`
Values for new entries in the Parse_Mode enum can be given as bitwise expressions, allowing bitwise ORs in calls to `get_keyval()`.

Also, by default `get_keyval()` should record the first time it has been called within that object, and avoid overriding the current value of a variable with the default value (allow multiple iterations of `init()`).

**Comment by jhenin** [comment]
Down the line, a more ambitious change will be to integrate the parser with the dependency system, so that parameters can behave like features.

**Comment by giacomofiorin** [comment]
Absolutely!  The feature class could in some way track whether the
corresponding flag has been set by the user after first object
construction.  This would allow initialization and multiple-copy
communication through the same infrastructure.

It's not so difficult to change the parser code accordingly, but rather
change the calls to get_keyval.  Perhaps we can do it progressively by
letting the old and new syntax to coexist for a time.

**Comment by giacomofiorin** [comment]
Absolutely!  The feature class could in some way track whether the corresponding flag has been set by the user after first object construction.  This would allow initialization and multiple-copy communication through the same infrastructure.

It's not so difficult to change the parser code accordingly, but rather change the calls to `get_keyval()` Perhaps we can do it progressively by letting the old and new syntax to coexist for a time.

**Comment by giacomofiorin** [comment]
Commit 4df07e2 implements the features-keywords integration.  Still missing is a check of whether the feature has been already set by the user previously.

**Comment by jhenin** [comment]
This features goes deep in the deps class, but only uses code from the parser class, rather than data structures. I have a variant in the deps branch (parse_user_feature() in ed7fdc2ccf097ae34401919e46a517cdb5449232) where it is implemented within colvardeps, with no changes to the feature_state class, and just an external call to colvarparse::get_keyval(), without inheritance between the two classes. Note that the whole thing does not compile yet because of extensive changes.

**Comment by giacomofiorin** [comment]
I like this, but would prefer to have the function named get_keyval() or in any case be named the same as the other parser calls to identify them all in a constructor or init() function by grep.

**Comment by jhenin** [comment]
I see. I used a different name just because it felt strange to have functions with the same name in different classes. And the overload is a bit messy, since the feature ids are integers, it would look  dangerously close to get_keyal for an int. Since what it does is a little different as well, how about a derived name: get_keyval_feature()? That works if you don't grep for the parenthesis.

**Comment by giacomofiorin** [comment]
OK with the name.  FYI, you can also still call it `get_keyval()` (same as the `colvarparse` version) and invoke it as `colvardeps::get_keyval()`.  Also, the positional parameters being in the same order would help.

**Comment by jhenin** [comment]
I think calling it colvardeps::get_keyval() may not make it clear enough what it is that the function actually does. Yes, I'll definitely reorder the parameters.

**Comment by giacomofiorin** [comment]
Regarding the improvement above (having a `Parse_Mode` value that makes `get_keyval()` handle the case of keywords not provided by the user): do you see an easy way to handle it through `colvardeps`?

Right now, it looks like each parameter keyword (for example: `forceConstant 5.0`) would need a corresponding feature ID to record whether the parameter has been provided (for example: `feature_states[f_cvb_force_k]->available = true;`). However, this is cumbersome (need to add many such IDs), and there may be a quicker way to do that?

**Comment by jhenin** [comment]
Good question. There's a conflict there between have the features be flexible and handle many different things, and having them behave in a uniform way.

I see only two choices, manually adding a feature for each parameter, or handling that automatically with the deps, either with a special kind of feature, or extending the existing feature arrays programmatically, which is possible but not used yet.

**Comment by giacomofiorin** [comment]
Pasting here issue #116 

_Would it make sense to add a parse_quiet mode, which only prints an output if the key is specified in the config string? That is, no output for the default value._

_Possibly offer that as a user option? The output would be less complete, but at this point it can get very long and hard to read._

**Comment by jhenin** [comment]
Going back to a previous point: 

> extending the existing feature arrays programmatically

One weakness here is that parameters are defined by calls to `get_keyval`, which indirectly defines an index of keywords valid for the current config string - since keywords that it doesn't catch are treated as errors. We could change `get_keyval` to enable a corresponding feature that it would look up by name. It would be "anonymous", since it wouldn't have a name in the feature enums.

Then I suppose whatever bit of code wants to use that feature can also look it up by parameter name. Actually, is_enabled() could be made polymorphic, and accept strings:

`if (is_enabled("lowerBoundary")) {`

Of course if we access that feature somewhere, it means we _could_ also add the corresponding feature manually (as was done with lowerBoundary). I'm not sure which is more elegant. We could even let a script parse the code for instances of get_keyval and generate the appropriate entries in the feature enums.

The downside I see with auto-generated features for every keyword is that many of them will stay unused and just clutter the dependency system.

**Comment by giacomofiorin** [comment]
I don't think that such a feature would be anonymous, since it would inherit the keyword as name?

However, if you start looking up a feature through a string identifier instead of an integer/enum, then you will also need to implement a hash table (or just use some of the existing STL containers?).  You would also need to make it case-insensitive.  I haven't looked yet at what the speed of access would be vs. a plain array.  If it doesn't make a difference, I'm OK with the hash table complement the array.

Perhaps we could add only the features that other keywords depend on, so that they are used by `get_kevyal()` to check whether a new keyword is "in-scope" or not.  This would eliminate a few hard-coded if-conditionals.

My feeling is that handling every user keyword through the dependency system is desirable but will be a long and gradual change.

I would focus for the moment on adding support for `parse_required` and `parse_quiet`, and file a separate issue about using the dependency system to check for supported keywords.
