### ISSUE TITLE
To benchmark : make group with very few atoms non-scalable by default

### ISSUE THREAD

**Issue by jhenin** [colvars/colvars#72]
At least for groups of a single atom, there must be some overhead we can avoid.

**Comment by giacomofiorin** [comment]
It certainly makes sense for optimization purposes.  Looking at the ComputeGlobal code, though, the overhead won't be very big.

**Comment by giacomofiorin** [comment]
It looks like this could be done by disabling `f_ag_scalable` in `cvm::atom_group::parse()`. Would this break the `f_cvc_scalable` dependency in the parent object at some point?

**Comment by jhenin** [comment]
I don't think so. We don't want to make scalable a hard dependency for cvcs anyway. One weird situation is, if a cvc has a small group and a large one, making the small one non-scalable will kill it for the whole cvc. So maybe it's a decision that needs to be taken at cvc level, looking at the size of the largest atom group? Now that's some logic that will never fit in the "deps" framework, but I don't think that's a problem.

**Comment by jhenin** [comment]
Ideally that decision could be made by the atom group and transparent for the CVC.

**Comment by giacomofiorin** [comment]
Yup. All the more reason to handle atomic coordinates and gradients in the
same object.

About the benchmark part, can  you give some numbers for systems that you
think would be affected?

On Mar 16, 2017 1:46 PM, "Jérôme Hénin" <notifications@github.com> wrote:

Ideally that decision could be made by the atom group and transparent for
the CVC.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/colvars/colvars/issues/72#issuecomment-287137489>, or mute
the thread

**Comment by jhenin** [comment]
Exactly, I was thinking of that, that definitely supports your argument.

I don't have a realistic benchmark. To be honest, if few atoms are involved, one could argue that it's going to be cheap either way, so any gains will be small. That's a fair point.

**Comment by jhenin** [comment]
Based on the discussion above, this is low-priority - closing.
