### ISSUE TITLE
ABF with dummy atoms under new force conventions

### ISSUE THREAD

**Issue by jeffcomer** [colvars/colvars#89]
After the major change in how forces are handled internally, I don't seem to be able to run ABF with dummy atoms as I did previously. I get the following error:

colvars:     # oneSiteTotalForce = on
colvars: Error: Feature unavailable: "compute total collective force only from one group center" in uninitialized cvc.

Is this something that needs to be implemented?

**Comment by giacomofiorin** [comment]
Hey Jeff, I presume that the dummy atom is not the one you're calculating the total force from, right?

As it turns out, the feature oneSiteTotalForce wasn't made available, and was de facto unusable. Commit 9151bb2 fixes this.

**Comment by jeffcomer** [comment]
Thanks a million, Giacomo. I recompiled NAMD with your commit. ABF with a dummy reference position is now working perfectly.

**Comment by vishnuprasad693** [comment]
The same error is being thrown up with LAMMPS (17 Nov 2016) colvars module when using oneSiteSystemForce. I tried making the above mentioned fix in the colvars library and recompiled, but seems to be of no use. Kindly help ( or is it better that i mention this in lammps mailing list?)

**Comment by giacomofiorin** [comment]
Hi Prasad, this is the right place to mention errors in the Colvars library.

Firstly, review the following:
https://colvars.github.io/totalforce.html
and change oneSiteSystemForce to oneSiteTotalForce, because the former is deprecated.

Secondly, you probably didn't update the Colvars library with the `update-colvars-code.sh` script: if you had done that, you wouldn't see the error.

Lastly, you can download the current version of LAMMPS from GitHub, and the error is fixed there (just tested).

**Comment by vishnuprasad693** [comment]
Thank You Giacomo. I downloaded and compiled current version of lammps from Github. It now works fine.
